export const schema = {
  model: 'user',
  fields: [
    'select.id',
    'select.name',
    'select.email',
    'select.age',
    'select.status',
    'select.profile.select.bio',
    'select.profile.select.website',
    'select.posts.select.title',
    'where.posts.some.title',
    'where.posts.every.id',
    'where.profile.bio',
    'where.AND[].age',
    'where.OR[].name',
    'where.NOT[].email',
    'where.status',
    'where.status.in[].ACTIVE',
    'where.status.notIn[].SUSPENDED',
    'where.tags.in',
    'where.tags.notIn',
    'where.email.contains',
    'where.email.startsWith',
    'where.email.endsWith',
    'where.posts.content.search',
  ],
};
